#!/bin/bash

SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"


if [[ -f $SCRIPT_FILE ]]; then
	echo file already exist
else
	echo '#!/bin/bash' > $SCRIPT_FILE
	chmod +x $SCRIPT_FILE
	subl $SCRIPT_FILE
	echo ================
	echo $1 created
	echo ================
fi
